test:
  adapter: postgresql
  encoding: unicode
  database: plant_test
  pool: 2


development:
  adapter: postgresql
  encoding: unicode
  database: plant_development
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  database: plant_production
  pool: 2
