test:
  adapter: sqlite3
  encoding: unicode
  database: plant_test.sqlite
  pool: 2


development:
  adapter: sqlite3
  encoding: unicode
  database: plant_development.sqlite
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  database: plant_production
  pool: 2
